export const communityContentDummy = [
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-02",
      job: "string",
      company: "string",
      company_public: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  // [
  //   {
  //     question_id: 2,
  //     user_templete_id: 2,
  //     question_content_id: 2,
  //     content: "string",
  //     category: "string",
  //     question: "string",
  //     created_at: "2024-01-04",
  //     job: "string",
  //     company: "string",
  //     company_public: 1,
  //     nickname: "string",
  //     profile: "string",
  //     affiliation_id: "string",
  //     likeCount: "string",
  //     commentCount: "string",
  //     myLikeSign: "string",
  //   },
  // ],
];
