export const communityContentDummy = [
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-01",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-02",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-03",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-04",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-05",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-06",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-07",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-08",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-09",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-10",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-11",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-12",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-13",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-14",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-15",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-16",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-17",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-18",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-19",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-21",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-22",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-23",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-24",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-25",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  [
    {
      question_id: 1,
      user_templete_id: 1,
      question_content_id: 1,
      content: "string",
      category: "string",
      question: "string",
      created_at: "2024-01-26",
      job: "string",
      company: "string",
      companyPublic: 1,
      nickname: "string",
      profile: "string",
      affiliation_id: "string",
      likeCount: "string",
      commentCount: "string",
      myLikeSign: "string",
    },
  ],
  // [
  //   {
  //     question_id: 2,
  //     user_templete_id: 2,
  //     question_content_id: 2,
  //     content: "string",
  //     category: "string",
  //     question: "string",
  //     created_at: "2024-01-04",
  //     job: "string",
  //     company: "string",
  //     companyPublic: 1,
  //     nickname: "string",
  //     profile: "string",
  //     affiliation_id: "string",
  //     likeCount: "string",
  //     commentCount: "string",
  //     myLikeSign: "string",
  //   },
  // ],
];
