export const stroyDummy = [
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
  {
    name: "지호지호짱",
    message: "ㄷㄹㅈㄷㄹㄷㅈㄹㄷㅈㄹㄷㅈㄹ",
    profile: "ㅋㅋ",
    position: "서비스 기획",
    company: "카카오",
    oneline: "카카오 메일의 서비스 기획 파트에서 어쩌구저쩌구 이러저러한 왁자지껄 일을 합니다 :)",
  },
];
